//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public string userid { get; set; }
        public string password { get; set; }
        public string rolename { get; set; }
        public string realname { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string depart { get; set; }
        public string title { get; set; }
        public string creator { get; set; }
        public string sex { get; set; }
    }
}
